[package]
name = "complex_app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
iced = { workspace = true }
iced_auravibe = { path = "../../uikit" }

[lints]
workspace = true
