[package]
name = "iced_auravibe"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = "1.25.0"
fontdue = "0.9.3"
iced = { workspace = true }
pollster = "0.4.0"
smallbox = "0.8.8"

[features]
debug = ["iced/hot"]

[lints]
workspace = true
